# ID da Organização no SonarCloud
sonar.organization=kghesitem

# Configurações do Projeto (Confirma este valor no painel do SonarCloud!)
sonar.projectKey=kghesitem_mimoquices-site
sonar.projectName=Mimoquices-site

# Diretórios incluídos e excluídos da análise
sonar.sources=app,resources,routes
sonar.exclusions=vendor/**,node_modules/**,storage/**,bootstrap/cache/**,public/**

# Codificação do texto
sonar.sourceEncoding=UTF-8