# ID da Organização no SonarCloud (Obrigatório para o Cloud)
sonar.organization=Kghesitem

# Configurações do Projeto
sonar.projectKey=Kghesitem_Mimoquices-site_67cb480e-ad74-485c-a627-4be429b655a5
sonar.projectName=Mimoquices-site

# Diretórios incluídos e excluídos da análise
sonar.sources=app,resources,routes
sonar.exclusions=vendor/**,node_modules/**,storage/**,bootstrap/cache/**,public/**

# Codificação do texto
sonar.sourceEncoding=UTF-8