name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Mantemos a validação só por segurança, mas podes apagar mais tarde
      - name: Validar se o Secret existe
        run: |
          if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
            echo "ATENÇÃO: O GitHub NÃO está a conseguir ler o SONAR_TOKEN!"
            exit 1
          else
            echo "O GitHub encontrou o SONAR_TOKEN com sucesso."
          fi

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.scanner.skipJreProvisioning=true